name: integration

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 14

      - name: unit-tests
        run: yarn test
